<?php

namespace wcs\GameOfThronesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoyaumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoyaumeRepository extends EntityRepository
{
}
